### ISSUE TITLE
The picker stays open initially. How can I show it only onClick?

### ISSUE THREAD

**Issue by tonysam** [Meshredded/react-simple-month-picker#2]

**Comment by FrenchTechLead** [comment]
This behaviour is not provided by react-simple-month-picker, i let the programer choose inside which container he want to put the component. it can be inside a popup for you  and in a sliding div for another programer. 
If you want it  to pop up onclick you can put the picker component inside a container that pops up just like this one : [react-popup ](https://www.npmjs.com/package/react-popup) and your code should look like something like this : 
```
import React from 'react';
import ReactDom from 'react-dom';
import Popup from 'react-popup';
import MonthPicker from 'react-simple-month-picker';

 
const MyPopup =  
<Popup
    className="mm-popup"
    btnClass="mm-popup__btn"
    closeBtn={true}
    closeHtml={null}
    defaultOk="Ok"
    defaultCancel="Cancel"
    wildClasses={false}
    closeOnOutsideClick={true} >
       <MonthPicker onChange={(date)=>{console.log(date);}} />
</Popup>
ReactDom.render(MyPopup, document.getElementById('popupContainer') );
```
